from seqtree import SequentialTreeSynthesizer


def print_table(title, rows):
    columns = list(rows[0])
    widths = {
        column: max(len(column), *(len(str(row[column])) for row in rows))
        for column in columns
    }

    print(title)
    print(" | ".join(column.ljust(widths[column]) for column in columns))
    print("-+-".join("-" * widths[column] for column in columns))
    for row in rows:
        print(" | ".join(str(row[column]).ljust(widths[column]) for column in columns))
    print()


data = [
    {"age": 24.5, "bmi": 21.3, "sex_code": 0, "income_bin": 1, "risk_code": 0},
    {"age": 31.2, "bmi": 25.1, "sex_code": 1, "income_bin": 1, "risk_code": 0},
    {"age": 45.8, "bmi": 27.4, "sex_code": 0, "income_bin": 2, "risk_code": 1},
    {"age": 52.1, "bmi": 29.9, "sex_code": 1, "income_bin": 2, "risk_code": 1},
    {"age": 67.4, "bmi": 31.2, "sex_code": 0, "income_bin": 3, "risk_code": 2},
    {"age": 73.0, "bmi": 30.5, "sex_code": 1, "income_bin": 3, "risk_code": 2},
]


model = SequentialTreeSynthesizer(
    optimize_order=True,
    tree_backend="auto",
    continuous_strategy="interpolate",
    continuous_columns=["age", "bmi"],
    n_jobs=-1,
    random_state=42,
    min_samples_leaf=1,
)
model.fit(data)
synthetic = model.sample(len(data), random_state=100)

print("Order:", model.get_variable_order())
print()
print_table("Real preprocessed input data", data)
print_table("Synthetic data generated by SeqTree", synthetic)
